# -*- coding: utf-8 -*-
"""DL_Exp8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1obj8Zi60XgmwOTQ-UCLhdO8Fl5kxuUYZ
"""

pip install lime tensorflow matplotlib numpy pandas

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical

from lime import lime_image
from skimage.segmentation import mark_boundaries

# -------------------------------
# 1. Load Dataset
# -------------------------------
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# Reshape for model
x_train_flat = x_train.reshape(-1, 784)
x_test_flat = x_test.reshape(-1, 784)

# One-hot encoding
y_train_cat = to_categorical(y_train, 10)
y_test_cat = to_categorical(y_test, 10)

# -------------------------------
# 2. Build Model (MLP)
# -------------------------------
model = Sequential([
    Dense(128, activation='relu', input_shape=(784,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train model
model.fit(x_train_flat, y_train_cat, epochs=5, batch_size=128, verbose=1)

# Evaluate
loss, acc = model.evaluate(x_test_flat, y_test_cat)
print("Test Accuracy:", acc)

# -------------------------------
# 3. Prediction Function for LIME
# -------------------------------
def predict_fn(images):
    # Convert to grayscale if 3 channels
    if images.shape[-1] == 3:
        images = np.mean(images, axis=-1)

    # Resize/reshape properly
    images = images.reshape(images.shape[0], -1)

    return model.predict(images)

# -------------------------------
# 4. Apply LIME
# -------------------------------
explainer = lime_image.LimeImageExplainer()

index = 0  # change index for different samples
image = x_test[index]

explanation = explainer.explain_instance(
    image,
    predict_fn,
    top_labels=1,
    hide_color=0,
    num_samples=1000
)

temp, mask = explanation.get_image_and_mask(
    explanation.top_labels[0],
    positive_only=True,
    num_features=5,
    hide_rest=False
)

# -------------------------------
# 5. Show LIME Explanation
# -------------------------------
plt.imshow(mark_boundaries(temp, mask))
plt.title("LIME Explanation")
plt.axis('off')
plt.show()

# -------------------------------
# 6. Generate Observation Table
# -------------------------------
results = []

for i in range(5):
    img = x_test[i]
    pred = np.argmax(model.predict(img.reshape(1, -1)))
    actual = y_test[i]

    results.append({
        "Sample": i,
        "Predicted": pred,
        "Actual": actual,
        "Correct": pred == actual
    })

df = pd.DataFrame(results)
print("\nObservation Table:\n")
print(df)