# -*- coding: utf-8 -*-
"""DL_LangChain_EXP07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iv_SeBS9dMEGXeEzvY6-DyotohDtf3tp
"""

!pip install langchain langchain-community langchain-core langchain-groq faiss-cpu sentence-transformers beautifulsoup4

import os
os.environ["GROQ_API_KEY"] = "YOUR_GROQ_API_KEY"

from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough

from langchain_groq import ChatGroq

def load_website(url):
    loader = WebBaseLoader(url)
    return loader.load()


def split_docs(docs):
    splitter = CharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=100
    )
    return splitter.split_documents(docs)


def create_db(chunks):
    embeddings = HuggingFaceEmbeddings(
        model_name="all-MiniLM-L6-v2"
    )
    return FAISS.from_documents(chunks, embeddings)



def get_retriever(db):
    return db.as_retriever(search_kwargs={"k": 4})



def load_llm():
    return ChatGroq(
        model="llama-3.1-8b-instant",
        temperature=0
    )



def build_chain(retriever, llm):

    prompt = ChatPromptTemplate.from_template(
        """Answer ONLY from the website content below.
If answer not found, say "Not available on website".

Context:
{context}

Question:
{question}

Answer:"""
    )

    chain = (
        {
            "context": retriever,
            "question": RunnablePassthrough()
        }
        | prompt
        | llm
    )

    return chain


def main():

    url = input("Enter website URL: ")

    print("\nLoading website...\n")

    docs = load_website(url)
    chunks = split_docs(docs)
    db = create_db(chunks)
    retriever = get_retriever(db)
    llm = load_llm()
    chain = build_chain(retriever, llm)

    print("\n===== WEBSITE BOT READY =====\n")

    while True:
        query = input("Ask question: ")

        if query.lower() == "exit":
            break

        response = chain.invoke(query)

        print("\nAnswer:\n", response.content)
        print("\n" + "="*50)



if __name__ == "__main__":
    main()